apiVersion: v2
actions:
  - name: Run kubectl
    events:
      - name: sh.keptn.event.deployment.triggered
    tasks:
      - name: Dump environment
        image: busybox
        cmd:
          - env
      - name: Deploy arbitrary k8s manifests
        image: "bitnami/kubectl"
        cmd:
          - kubectl
        args:
          - '--server=https://kubernetes.default.svc'
            '--certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
          - '--token=/var/run/secrets/kubernetes.io/serviceaccount/token'
          - 'version'
