apiVersion: v2
actions:
  - name: Run kubectl
    events:
      - name: sh.keptn.event.deployment.triggered
    tasks:
      - name: Deploy arbitrary k8s manifests
        image: "bitnami/kubectl"
        cmd:
          - kubectl
        args:
          - 'version'
